### ISSUE TITLE
Displaying time left to the beginning of the concert

### ISSUE THREAD

**Issue by tulinkry** [bigbandbiskupska/bigbandbiskupska#47]
I believe that there was a bootstrap badge displaying how much time is left to the beginning of the concert. It was at least at the concerts page.

**Comment by veverma4** [comment]
I believe not.

**Comment by tulinkry** [comment]
Anyway fix it

**Comment by tulinkry** [comment]
I knew I wrote it before. I don't remember why I commented that out.

https://github.com/bigbandbiskupska/bigbandbiskupska/blob/193e86d403ff2951cf1634a92088489b7fee4fe1/app/front/presenters/templates/Homepage/default.latte#L53
