### ISSUE TITLE
In the mobile version it is not possible to change language

### ISSUE THREAD

**Issue by veverma4** [bigbandbiskupska/bigbandbiskupska#54]
@tulinkry 
The hamburger menu closes after clicking on flag

**Comment by tulinkry** [comment]
Wth is hamburger menu?

**Comment by veverma4** [comment]
![top-header-image1](https://cloud.githubusercontent.com/assets/9808924/24653310/9bd695c0-1935-11e7-8e18-3b3743b04c63.jpg)

**Comment by veverma4** [comment]
Well that still doesn't solve the problem - the language does not change after clicking on flag
![01](https://cloud.githubusercontent.com/assets/9808924/24674612/576bd926-197c-11e7-847f-2155a32ebe0c.PNG)
![02](https://cloud.githubusercontent.com/assets/9808924/24674614/591358b2-197c-11e7-90f7-c3173176e864.PNG)

**Comment by tulinkry** [comment]
It shouldn't. It uncollapses the language menu and then you can choose the language.

Markéta Veverková <notifications@github.com>napsal/a:

**Comment by veverma4** [comment]
Okay, haven't noticed that it wants me to scroll, intuitivity 2/10

**Comment by tulinkry** [comment]
Care to finish it?

Markéta Veverková <notifications@github.com>napsal/a:

**Comment by veverma4** [comment]
No time for that #stayBusy

**Comment by tulinkry** [comment]
Finished with new language menu 
![screenshot from 2017-04-15 23-15-55](https://cloud.githubusercontent.com/assets/6997160/25066802/84915684-2231-11e7-8171-9b9f461cd8d6.png)
